on: push
name: CI

jobs:
  build:
    uses: BattletechModders/ModTek/.github/workflows/mod-builder.yml@master
    with:
      checkout-directory: 'BATTLETECH/Mods/MechEngineer'
      build-script: |
        (
          cd ..
          curl -L -o CustomComponents.zip https://github.com/BattletechModders/CustomComponents/releases/download/latest/CustomComponents.zip
          unzip CustomComponents.zip
        )
        (
          cd ..
          curl -L -o CustomFilters.zip https://github.com/BattletechModders/CustomFilters/releases/download/latest/CustomFilters.zip
          unzip CustomFilters.zip
        )
        (
          cd source
          dotnet build -c Release -p:BattleTechGameDir="$BATTLETECH_DIR/"
        )
        (
          cd ..
          7z a -tzip "MechEngineer.zip" \
            MechEngineer/ \
            -xr!source "-xr!.*"
        )
        (
          cd ..
          mkdir all && cd all
          unzip ../CustomComponents.zip
          unzip ../CustomFilters.zip
          unzip ../MechEngineer.zip
          7z a -tzip -mx9 "$DIST_DIR/MechEngineer.zip" .
        )
      release-notes: |
        Requires ModTek v4.3 or later.
        MechEngineer.zip contains:
          - MechEngineer
          - [CustomComponents](https://github.com/BattletechModders/CustomComponents) (Required)
          - [CustomFilters](https://github.com/BattletechModders/CustomFilters) (Recommended)
    secrets: inherit
